export const displayVariants = {
  display: {
    block: 'block',
    inline: 'inline',
    'inline-block': 'inline-block',
    flex: 'flex',
    'inline-flex': 'inline-flex',
    grid: 'grid',
    'inline-grid': 'inline-grid',
    none: 'hidden',
  },
  'display-sm': {
    block: 'sm:block',
    inline: 'sm:inline',
    'inline-block': 'sm:inline-block',
    flex: 'sm:flex',
    'inline-flex': 'sm:inline-flex',
    grid: 'sm:grid',
    'inline-grid': 'sm:inline-grid',
    none: 'sm:hidden',
  },
  'display-md': {
    block: 'md:block',
    inline: 'md:inline',
    'inline-block': 'md:inline-block',
    flex: 'md:flex',
    'inline-flex': 'md:inline-flex',
    grid: 'md:grid',
    'inline-grid': 'md:inline-grid',
    none: 'md:hidden',
  },
  'display-lg': {
    block: 'lg:block',
    inline: 'lg:inline',
    'inline-block': 'lg:inline-block',
    flex: 'lg:flex',
    'inline-flex': 'lg:inline-flex',
    grid: 'lg:grid',
    'inline-grid': 'lg:inline-grid',
    none: 'lg:hidden',
  },
  'display-xl': {
    block: 'xl:block',
    inline: 'xl:inline',
    'inline-block': 'xl:inline-block',
    flex: 'xl:flex',
    'inline-flex': 'xl:inline-flex',
    grid: 'xl:grid',
    'inline-grid': 'xl:inline-grid',
    none: 'xl:hidden',
  },
}
