export const borderRadiusVariants = {
  'border-radius': {
    xs: 'rounded-xs',
    sm: 'rounded-sm',
    md: 'rounded-md',
    lg: 'rounded-lg',
    xl: 'rounded-xl',
    '2xl': 'rounded-2xl',
    '3xl': 'rounded-3xl',
    none: 'rounded-none',
    full: 'rounded-full',
  },
  'border-radius-sm': {
    xs: 'sm:rounded-sm',
    sm: 'sm:rounded-md',
    md: 'sm:rounded-lg',
    lg: 'sm:rounded-xl',
    xl: 'sm:rounded-2xl',
    '2xl': 'sm:rounded-3xl',
    none: 'sm:rounded-none',
    full: 'sm:rounded-full',
  },
  'border-radius-md': {
    xs: 'md:rounded-xs',
    sm: 'md:rounded-sm',
    md: 'md:rounded-md',
    lg: 'md:rounded-lg',
    xl: 'md:rounded-xl',
    '2xl': 'md:rounded-2xl',
    '3xl': 'md:rounded-3xl',
    none: 'md:rounded-none',
    full: 'md:rounded-full',
  },
  'border-radius-lg': {
    xs: 'lg:rounded-xs',
    sm: 'lg:rounded-sm',
    md: 'lg:rounded-md',
    lg: 'lg:rounded-lg',
    xl: 'lg:rounded-xl',
    '2xl': 'lg:rounded-2xl',
    '3xl': 'lg:rounded-3xl',
    none: 'lg:rounded-none',
    full: 'lg:rounded-full',
  },
  'border-radius-xl': {
    xs: 'xl:rounded-xs',
    sm: 'xl:rounded-sm',
    md: 'xl:rounded-md',
    lg: 'xl:rounded-lg',
    xl: 'xl:rounded-xl',
    '2xl': 'xl:rounded-2xl',
    '3xl': 'xl:rounded-3xl',
    none: 'xl:rounded-none',
    full: 'xl:rounded-full',
  },
}
