export const borderVariants = {
  border: {
    0: 'border-0',
    1: 'border',
    2: 'border-2',
    4: 'border-4',
    8: 'border-8',
    px: 'border',
    none: 'border-0',
  },
  'border-sm': {
    0: 'sm:border-0',
    1: 'sm:border',
    2: 'sm:border-2',
    4: 'sm:border-4',
    8: 'sm:border-8',
    px: 'sm:border',
    none: 'sm:border-0',
  },
  'border-md': {
    0: 'md:border-0',
    1: 'md:border',
    2: 'md:border-2',
    4: 'md:border-4',
    8: 'md:border-8',
    px: 'md:border',
    none: 'md:border-0',
  },
  'border-lg': {
    0: 'lg:border-0',
    1: 'lg:border',
    2: 'lg:border-2',
    4: 'lg:border-4',
    8: 'lg:border-8',
    px: 'lg:border',
    none: 'lg:border-0',
  },
  'border-xl': {
    0: 'xl:border-0',
    1: 'xl:border',
    2: 'xl:border-2',
    4: 'xl:border-4',
    8: 'xl:border-8',
    px: 'xl:border',
    none: 'xl:border-0',
  },
  'border-t': {
    0: 'border-t-0',
    1: 'border-t',
    2: 'border-t-2',
    4: 'border-t-4',
    8: 'border-t-8',
    px: 'border-t',
    none: 'border-t-0',
  },
  'border-t-sm': {
    0: 'sm:border-t-0',
    1: 'sm:border-t',
    2: 'sm:border-t-2',
    4: 'sm:border-t-4',
    8: 'sm:border-t-8',
    px: 'sm:border-t',
    none: 'sm:border-t-0',
  },
  'border-t-md': {
    0: 'md:border-t-0',
    1: 'md:border-t',
    2: 'md:border-t-2',
    4: 'md:border-t-4',
    8: 'md:border-t-8',
    px: 'md:border-t',
    none: 'md:border-t-0',
  },
  'border-t-lg': {
    0: 'lg:border-t-0',
    1: 'lg:border-t',
    2: 'lg:border-t-2',
    4: 'lg:border-t-4',
    8: 'lg:border-t-8',
    px: 'lg:border-t',
    none: 'lg:border-t-0',
  },
  'border-t-xl': {
    0: 'xl:border-t-0',
    1: 'xl:border-t',
    2: 'xl:border-t-2',
    4: 'xl:border-t-4',
    8: 'xl:border-t-8',
    px: 'xl:border-t',
    none: 'xl:border-t-0',
  },
  'border-b': {
    0: 'border-b-0',
    1: 'border-b',
    2: 'border-b-2',
    4: 'border-b-4',
    8: 'border-b-8',
    px: 'border-b',
  },
  'border-b-sm': {
    0: 'sm:border-b-0',
    1: 'sm:border-b',
    2: 'sm:border-b-2',
    4: 'sm:border-b-4',
    8: 'sm:border-b-8',
    px: 'sm:border-b',
    none: 'sm:border-b-0',
  },
  'border-b-md': {
    0: 'md:border-b-0',
    1: 'md:border-b',
    2: 'md:border-b-2',
    4: 'md:border-b-4',
    8: 'md:border-b-8',
    px: 'md:border-b',
    none: 'md:border-b-0',
  },
  'border-b-lg': {
    0: 'lg:border-b-0',
    1: 'lg:border-b',
    2: 'lg:border-b-2',
    4: 'lg:border-b-4',
    8: 'lg:border-b-8',
    px: 'lg:border-b',
    none: 'lg:border-b-0',
  },
  'border-b-xl': {
    0: 'xl:border-b-0',
    1: 'xl:border-b',
    2: 'xl:border-b-2',
    4: 'xl:border-b-4',
    8: 'xl:border-b-8',
    px: 'xl:border-b',
    none: 'xl:border-b-0',
  },
  'border-r': {
    0: 'border-r-0',
    1: 'border-r',
    2: 'border-r-2',
    4: 'border-r-4',
    8: 'border-r-8',
    px: 'border-r',
    none: 'border-r-0',
  },
  'border-r-sm': {
    0: 'sm:border-r-0',
    1: 'sm:border-r',
    2: 'sm:border-r-2',
    4: 'sm:border-r-4',
    8: 'sm:border-r-8',
    px: 'sm:border-r',
    none: 'sm:border-r-0',
  },
  'border-r-md': {
    0: 'md:border-r-0',
    1: 'md:border-r',
    2: 'md:border-r-2',
    4: 'md:border-r-4',
    8: 'md:border-r-8',
    px: 'md:border-r',
    none: 'md:border-r-0',
  },
  'border-r-lg': {
    0: 'lg:border-r-0',
    1: 'lg:border-r',
    2: 'lg:border-r-2',
    4: 'lg:border-r-4',
    8: 'lg:border-r-8',
    px: 'lg:border-r',
    none: 'lg:border-r-0',
  },
  'border-r-xl': {
    0: 'xl:border-r-0',
    1: 'xl:border-r',
    2: 'xl:border-r-2',
    4: 'xl:border-r-4',
    8: 'xl:border-r-8',
    px: 'xl:border-r',
    none: 'xl:border-r-0',
  },
  'border-l': {
    0: 'border-l-0',
    1: 'border-l',
    2: 'border-l-2',
    4: 'border-l-4',
    8: 'border-l-8',
    px: 'border-l',
    none: 'border-l-0',
  },
  'border-l-sm': {
    0: 'sm:border-l-0',
    1: 'sm:border-l',
    2: 'sm:border-l-2',
    4: 'sm:border-l-4',
    8: 'sm:border-l-8',
    px: 'sm:border-l',
    none: 'sm:border-l-0',
  },
  'border-l-md': {
    0: 'md:border-l-0',
    1: 'md:border-l',
    2: 'md:border-l-2',
    4: 'md:border-l-4',
    8: 'md:border-l-8',
    px: 'md:border-l',
    none: 'md:border-l-0',
  },
  'border-l-lg': {
    0: 'lg:border-l-0',
    1: 'lg:border-l',
    2: 'lg:border-l-2',
    4: 'lg:border-l-4',
    8: 'lg:border-l-8',
    px: 'lg:border-l',
    none: 'lg:border-l-0',
  },
  'border-l-xl': {
    0: 'xl:border-l-0',
    1: 'xl:border-l',
    2: 'xl:border-l-2',
    4: 'xl:border-l-4',
    8: 'xl:border-l-8',
    px: 'xl:border-l',
    none: 'xl:border-l-0',
  },
  'border-y': {
    0: 'border-y-0',
    1: 'border-y',
    2: 'border-y-2',
    4: 'border-y-4',
    8: 'border-y-8',
    px: 'border-y',
    none: 'border-y-0',
  },
  'border-y-sm': {
    0: 'sm:border-y-0',
    1: 'sm:border-y',
    2: 'sm:border-y-2',
    4: 'sm:border-y-4',
    8: 'sm:border-y-8',
    px: 'sm:border-y',
    none: 'sm:border-y-0',
  },
  'border-y-md': {
    0: 'md:border-y-0',
    1: 'md:border-y',
    2: 'md:border-y-2',
    4: 'md:border-y-4',
    8: 'md:border-y-8',
    px: 'md:border-y',
    none: 'md:border-y-0',
  },
  'border-y-lg': {
    0: 'lg:border-y-0',
    1: 'lg:border-y',
    2: 'lg:border-y-2',
    4: 'lg:border-y-4',
    8: 'lg:border-y-8',
    px: 'lg:border-y',
    none: 'lg:border-y-0',
  },
  'border-y-xl': {
    0: 'xl:border-y-0',
    1: 'xl:border-y',
    2: 'xl:border-y-2',
    4: 'xl:border-y-4',
    8: 'xl:border-y-8',
    px: 'xl:border-y',
    none: 'xl:border-y-0',
  },
  'border-x': {
    0: 'border-x-0',
    1: 'border-x',
    2: 'border-x-2',
    4: 'border-x-4',
    8: 'border-x-8',
    px: 'border-x',
    none: 'border-x-0',
  },
  'border-x-sm': {
    0: 'sm:border-x-0',
    1: 'sm:border-x',
    2: 'sm:border-x-2',
    4: 'sm:border-x-4',
    8: 'sm:border-x-8',
    px: 'sm:border-x',
    none: 'sm:border-x-0',
  },
  'border-x-md': {
    0: 'md:border-x-0',
    1: 'md:border-x',
    2: 'md:border-x-2',
    4: 'md:border-x-4',
    8: 'md:border-x-8',
    px: 'md:border-x',
    none: 'md:border-x-0',
  },
  'border-x-lg': {
    0: 'lg:border-x-0',
    1: 'lg:border-x',
    2: 'lg:border-x-2',
    4: 'lg:border-x-4',
    8: 'lg:border-x-8',
    px: 'lg:border-x',
    none: 'lg:border-x-0',
  },
  'border-x-xl': {
    0: 'xl:border-x-0',
    1: 'xl:border-x',
    2: 'xl:border-x-2',
    4: 'xl:border-x-4',
    8: 'xl:border-x-8',
    px: 'xl:border-x',
    none: 'xl:border-x-0',
  },
}
