export const colEndVariants = {
  'col-end': {
    '-1': '-col-end-1',
    1: 'col-end-1',
    2: 'col-end-2',
    3: 'col-end-3',
    4: 'col-end-4',
    5: 'col-end-5',
    6: 'col-end-6',
    7: 'col-end-7',
    8: 'col-end-8',
    9: 'col-end-9',
    10: 'col-end-10',
    11: 'col-end-11',
    12: 'col-end-12',
  },
  'col-end-md': {
    '-1': 'md:-col-end-1',
    1: 'md:col-end-1',
    2: 'md:col-end-2',
    3: 'md:col-end-3',
    4: 'md:col-end-4',
    5: 'md:col-end-5',
    6: 'md:col-end-6',
    7: 'md:col-end-7',
    8: 'md:col-end-8',
    9: 'md:col-end-9',
    10: 'md:col-end-10',
    11: 'md:col-end-11',
    12: 'md:col-end-12',
  },
  'col-end-lg': {
    '-1': 'lg:-col-end-1',
    1: 'lg:col-end-1',
    2: 'lg:col-end-2',
    3: 'lg:col-end-3',
    4: 'lg:col-end-4',
    5: 'lg:col-end-5',
    6: 'lg:col-end-6',
    7: 'lg:col-end-7',
    8: 'lg:col-end-8',
    9: 'lg:col-end-9',
    10: 'lg:col-end-10',
    11: 'lg:col-end-11',
    12: 'lg:col-end-12',
  },
  'col-end-xl': {
    '-1': 'xl:-col-end-1',
    1: 'xl:col-end-1',
    2: 'xl:col-end-2',
    3: 'xl:col-end-3',
    4: 'xl:col-end-4',
    5: 'xl:col-end-5',
    6: 'xl:col-end-6',
    7: 'xl:col-end-7',
    8: 'xl:col-end-8',
    9: 'xl:col-end-9',
    10: 'xl:col-end-10',
    11: 'xl:col-end-11',
    12: 'xl:col-end-12',
  },
}
