export const gridPlaceItemsVariants = {
  'place-items': {
    baseline: 'place-items-baseline',
    center: 'place-items-center',
    'center-safe': 'place-items-center-safe',
    start: 'place-items-start',
    end: 'place-items-end',
    'end-safe': 'place-items-end-safe',
    stretch: 'place-items-stretch',
  },
  'place-items-sm': {
    baseline: 'sm:place-items-baseline',
    center: 'sm:place-items-center',
    'center-safe': 'sm:place-items-center-safe',
    start: 'sm:place-items-start',
    end: 'sm:place-items-end',
    'end-safe': 'sm:place-items-end-safe',
    stretch: 'sm:place-items-stretch',
  },
  'place-items-md': {
    baseline: 'md:place-items-baseline',
    center: 'md:place-items-center',
    'center-safe': 'md:place-items-center-safe',
    start: 'md:place-items-start',
    end: 'md:place-items-end',
    'end-safe': 'md:place-items-end-safe',
    stretch: 'md:place-items-stretch',
  },
  'place-items-lg': {
    baseline: 'lg:place-items-baseline',
    center: 'lg:place-items-center',
    'center-safe': 'lg:place-items-center-safe',
    start: 'lg:place-items-start',
    end: 'lg:place-items-end',
    'end-safe': 'lg:place-items-end-safe',
    stretch: 'lg:place-items-stretch',
  },
  'place-items-xl': {
    baseline: 'xl:place-items-baseline',
    center: 'xl:place-items-center',
    'center-safe': 'xl:place-items-center-safe',
    start: 'xl:place-items-start',
    end: 'xl:place-items-end',
    'end-safe': 'xl:place-items-end-safe',
    stretch: 'xl:place-items-stretch',
  },
}
