export const rowStartVariants = {
  'row-start': {
    '-1': '-row-start-1',
    1: 'row-start-1',
    2: 'row-start-2',
    3: 'row-start-3',
    4: 'row-start-4',
    5: 'row-start-5',
    6: 'row-start-6',
    7: 'row-start-7',
    8: 'row-start-8',
    9: 'row-start-9',
    10: 'row-start-10',
    11: 'row-start-11',
    12: 'row-start-12',
  },
  'row-start-md': {
    '-1': 'md:-row-start-1',
    1: 'md:row-start-1',
    2: 'md:row-start-2',
    3: 'md:row-start-3',
    4: 'md:row-start-4',
    5: 'md:row-start-5',
    6: 'md:row-start-6',
    7: 'md:row-start-7',
    8: 'md:row-start-8',
    9: 'md:row-start-9',
    10: 'md:row-start-10',
    11: 'md:row-start-11',
    12: 'md:row-start-12',
  },
  'row-start-lg': {
    '-1': 'lg:-row-start-1',
    1: 'lg:row-start-1',
    2: 'lg:row-start-2',
    3: 'lg:row-start-3',
    4: 'lg:row-start-4',
    5: 'lg:row-start-5',
    6: 'lg:row-start-6',
    7: 'lg:row-start-7',
    8: 'lg:row-start-8',
    9: 'lg:row-start-9',
    10: 'lg:row-start-10',
    11: 'lg:row-start-11',
    12: 'lg:row-start-12',
  },
  'row-start-xl': {
    '-1': 'xl:-row-start-1',
    1: 'xl:row-start-1',
    2: 'xl:row-start-2',
    3: 'xl:row-start-3',
    4: 'xl:row-start-4',
    5: 'xl:row-start-5',
    6: 'xl:row-start-6',
    7: 'xl:row-start-7',
    8: 'xl:row-start-8',
    9: 'xl:row-start-9',
    10: 'xl:row-start-10',
    11: 'xl:row-start-11',
    12: 'xl:row-start-12',
  },
}
