export const rowEndVariants = {
  'row-end': {
    '-1': '-row-end-1',
    1: 'row-end-1',
    2: 'row-end-2',
    3: 'row-end-3',
    4: 'row-end-4',
    5: 'row-end-5',
    6: 'row-end-6',
    7: 'row-end-7',
    8: 'row-end-8',
    9: 'row-end-9',
    10: 'row-end-10',
    11: 'row-end-11',
    12: 'row-end-12',
  },
  'row-end-md': {
    '-1': 'md:-row-end-1',
    1: 'md:row-end-1',
    2: 'md:row-end-2',
    3: 'md:row-end-3',
    4: 'md:row-end-4',
    5: 'md:row-end-5',
    6: 'md:row-end-6',
    7: 'md:row-end-7',
    8: 'md:row-end-8',
    9: 'md:row-end-9',
    10: 'md:row-end-10',
    11: 'md:row-end-11',
    12: 'md:row-end-12',
  },
  'row-end-lg': {
    '-1': 'lg:-row-end-1',
    1: 'lg:row-end-1',
    2: 'lg:row-end-2',
    3: 'lg:row-end-3',
    4: 'lg:row-end-4',
    5: 'lg:row-end-5',
    6: 'lg:row-end-6',
    7: 'lg:row-end-7',
    8: 'lg:row-end-8',
    9: 'lg:row-end-9',
    10: 'lg:row-end-10',
    11: 'lg:row-end-11',
    12: 'lg:row-end-12',
  },
  'row-end-xl': {
    '-1': 'xl:-row-end-1',
    1: 'xl:row-end-1',
    2: 'xl:row-end-2',
    3: 'xl:row-end-3',
    4: 'xl:row-end-4',
    5: 'xl:row-end-5',
    6: 'xl:row-end-6',
    7: 'xl:row-end-7',
    8: 'xl:row-end-8',
    9: 'xl:row-end-9',
    10: 'xl:row-end-10',
    11: 'xl:row-end-11',
    12: 'xl:row-end-12',
  },
}
