export const rowSpanVariants = {
  'row-span': {
    1: 'row-span-1',
    2: 'row-span-2',
    3: 'row-span-3',
    4: 'row-span-4',
    5: 'row-span-5',
    6: 'row-span-6',
    7: 'row-span-7',
    8: 'row-span-8',
    9: 'row-span-9',
    10: 'row-span-10',
    11: 'row-span-11',
    12: 'row-span-12',
    full: 'row-span-full',
  },
  'row-span-md': {
    1: 'md:row-span-1',
    2: 'md:row-span-2',
    3: 'md:row-span-3',
    4: 'md:row-span-4',
    5: 'md:row-span-5',
    6: 'md:row-span-6',
    7: 'md:row-span-7',
    8: 'md:row-span-8',
    9: 'md:row-span-9',
    10: 'md:row-span-10',
    11: 'md:row-span-11',
    12: 'md:row-span-12',
    full: 'md:row-span-full',
  },
  'row-span-lg': {
    1: 'lg:row-span-1',
    2: 'lg:row-span-2',
    3: 'lg:row-span-3',
    4: 'lg:row-span-4',
    5: 'lg:row-span-5',
    6: 'lg:row-span-6',
    7: 'lg:row-span-7',
    8: 'lg:row-span-8',
    9: 'lg:row-span-9',
    10: 'lg:row-span-10',
    11: 'lg:row-span-11',
    12: 'lg:row-span-12',
    full: 'lg:row-span-full',
  },
  'row-span-xl': {
    1: 'xl:row-span-1',
    2: 'xl:row-span-2',
    3: 'xl:row-span-3',
    4: 'xl:row-span-4',
    5: 'xl:row-span-5',
    6: 'xl:row-span-6',
    7: 'xl:row-span-7',
    8: 'xl:row-span-8',
    9: 'xl:row-span-9',
    10: 'xl:row-span-10',
    11: 'xl:row-span-11',
    12: 'xl:row-span-12',
    full: 'xl:row-span-full',
  },
}
