export const lineClampVariants = {
  'line-clamp': {
    1: 'line-clamp-1',
    2: 'line-clamp-2',
    3: 'line-clamp-3',
    4: 'line-clamp-4',
    5: 'line-clamp-5',
    6: 'line-clamp-6',
    none: 'line-clamp-none',
  },
  'line-clamp-sm': {
    1: 'sm:line-clamp-1',
    2: 'sm:line-clamp-2',
    3: 'sm:line-clamp-3',
    4: 'sm:line-clamp-4',
    5: 'sm:line-clamp-5',
    6: 'sm:line-clamp-6',
    none: 'sm:line-clamp-none',
  },
  'line-clamp-md': {
    1: 'md:line-clamp-1',
    2: 'md:line-clamp-2',
    3: 'md:line-clamp-3',
    4: 'md:line-clamp-4',
    5: 'md:line-clamp-5',
    6: 'md:line-clamp-6',
    none: 'md:line-clamp-none',
  },
  'line-clamp-lg': {
    1: 'lg:line-clamp-1',
    2: 'lg:line-clamp-2',
    3: 'lg:line-clamp-3',
    4: 'lg:line-clamp-4',
    5: 'lg:line-clamp-5',
    6: 'lg:line-clamp-6',
    none: 'lg:line-clamp-none',
  },
  'line-clamp-xl': {
    1: 'xl:line-clamp-1',
    2: 'xl:line-clamp-2',
    3: 'xl:line-clamp-3',
    4: 'xl:line-clamp-4',
    5: 'xl:line-clamp-5',
    6: 'xl:line-clamp-6',
    none: 'xl:line-clamp-none',
  },
}
