export const verticalAlignVariants = {
  'vertical-align': {
    baseline: 'align-baseline',
    top: 'align-top',
    middle: 'align-middle',
    bottom: 'align-bottom',
    'text-top': 'align-text-top',
    'text-bottom': 'align-text-bottom',
    sub: 'align-sub',
    super: 'align-super',
  },
  'vertical-align-sm': {
    baseline: 'sm:align-baseline',
    top: 'sm:align-top',
    middle: 'sm:align-middle',
    bottom: 'sm:align-bottom',
    'text-top': 'sm:align-text-top',
    'text-bottom': 'sm:align-text-bottom',
    sub: 'sm:align-sub',
    super: 'sm:align-super',
  },
  'vertical-align-md': {
    baseline: 'md:align-baseline',
    top: 'md:align-top',
    middle: 'md:align-middle',
    bottom: 'md:align-bottom',
    'text-top': 'md:align-text-top',
    'text-bottom': 'md:align-text-bottom',
    sub: 'md:align-sub',
    super: 'md:align-super',
  },
  'vertical-align-lg': {
    baseline: 'lg:align-baseline',
    top: 'lg:align-top',
    middle: 'lg:align-middle',
    bottom: 'lg:align-bottom',
    'text-top': 'lg:align-text-top',
    'text-bottom': 'lg:align-text-bottom',
    sub: 'lg:align-sub',
    super: 'lg:align-super',
  },
  'vertical-align-xl': {
    baseline: 'xl:align-baseline',
    top: 'xl:align-top',
    middle: 'xl:align-middle',
    bottom: 'xl:align-bottom',
    'text-top': 'xl:align-text-top',
    'text-bottom': 'xl:align-text-bottom',
    sub: 'xl:align-sub',
    super: 'xl:align-super',
  },
}
