export const whiteSpaceVariants = {
  'white-space': {
    normal: 'whitespace-normal',
    nowrap: 'whitespace-nowrap',
    pre: 'whitespace-pre',
    'pre-line': 'whitespace-pre-line',
    'pre-wrap': 'whitespace-pre-wrap',
    break: 'whitespace-break-spaces',
  },
  'white-space-sm': {
    normal: 'sm:whitespace-normal',
    nowrap: 'sm:whitespace-nowrap',
    pre: 'sm:whitespace-pre',
    'pre-line': 'sm:whitespace-pre-line',
    'pre-wrap': 'sm:whitespace-pre-wrap',
    break: 'sm:whitespace-break-spaces',
  },
  'white-space-md': {
    normal: 'md:whitespace-normal',
    nowrap: 'md:whitespace-nowrap',
    pre: 'md:whitespace-pre',
    'pre-line': 'md:whitespace-pre-line',
    'pre-wrap': 'md:whitespace-pre-wrap',
    break: 'md:whitespace-break-spaces',
  },
  'white-space-lg': {
    normal: 'lg:whitespace-normal',
    nowrap: 'lg:whitespace-nowrap',
    pre: 'lg:whitespace-pre',
    'pre-line': 'lg:whitespace-pre-line',
    'pre-wrap': 'lg:whitespace-pre-wrap',
    break: 'lg:whitespace-break-spaces',
  },
  'white-space-xl': {
    normal: 'xl:whitespace-normal',
    nowrap: 'xl:whitespace-nowrap',
    pre: 'xl:whitespace-pre',
    'pre-line': 'xl:whitespace-pre-line',
    'pre-wrap': 'xl:whitespace-pre-wrap',
    break: 'xl:whitespace-break-spaces',
  },
}
