export const outlineWidthVariants = {
  outline: {
    0: 'outline-0',
    1: 'outline',
    2: 'outline-2',
    4: 'outline-4',
    8: 'outline-8',
    px: 'outline',
    none: 'outline-0',
  },
  'outline-sm': {
    0: 'sm:outline-0',
    1: 'sm:outline',
    2: 'sm:outline-2',
    4: 'sm:outline-4',
    8: 'sm:outline-8',
    px: 'sm:outline',
    none: 'sm:outline-0',
  },
  'outline-md': {
    0: 'md:outline-0',
    1: 'md:outline',
    2: 'md:outline-2',
    4: 'md:outline-4',
    8: 'md:outline-8',
    px: 'md:outline',
    none: 'md:outline-0',
  },
  'outline-lg': {
    0: 'lg:outline-0',
    1: 'lg:outline',
    2: 'lg:outline-2',
    4: 'lg:outline-4',
    8: 'lg:outline-8',
    px: 'lg:outline',
    none: 'lg:outline-0',
  },
  'outline-xl': {
    0: 'xl:outline-0',
    1: 'xl:outline',
    2: 'xl:outline-2',
    4: 'xl:outline-4',
    8: 'xl:outline-8',
    px: 'xl:outline',
    none: 'xl:outline-0',
  },
}
